# config for analysis
aggregate_fract_infect_csvs: results/neut_titers/fracinfect.csv

elisa_data_dir: data/rbd_depletion_elisas
elisa_data_files:
  - 08Oct21_ELISA.csv
  - 15Oct21_ELISA.csv
  - 06Dec21_ELISA.csv
  - 08Dec21_ELISA.csv
  - 08Dec21_D614G_ELISA.csv
  - 20Dec21_D614G_ELISA.csv

depletions:
  - mock depleted
  - 1x depleted
  - 2x depleted
  - 3x depleted
  - 4x depleted

haarvi_rbd_depletions: data/haarvi_rbd_depletion_foldchange_ic50.csv

# enter all the samples and stuff to ignore here
neut_samples_ignore: False

# the neutralization limit of detection is equal to the starting dilution
NT50_LOD: 25

rbd_depletions_date:
  - 2021-11-12
  - 2021-11-25
  - 2021-12-12
  - 2021-12-22
  - 2022-01-06

heterologous_depletions_dates:
  - 2021-11-25
  - 2022-01-06

sample_key_file: data/sample_key.csv

sample_type_order:
  - Pfizer
  - Delta breakthrough
  - primary Delta infection

virus_key_mutneuts: # how to rename viruses for analyzing mutneuts
  RBD antibodies depleted (D614G spike): D614G RBD Abs depleted (x D614G PV)
  mock depletion (D614G spike): D614G
  RBD antibodies depleted (Delta spike): Delta RBD Abs depleted (x Delta PV)
  mock depletion (Delta spike): Delta
  Delta RBD antibodies depleted x D614G spike PV: Delta RBD Abs depleted (x D614G PV)
  Delta_E484K: Delta + E484K
  Delta_K417N: Delta + K417N
  Delta: Delta

virus_order:
  - D614G
  - Delta
  - Delta + K417N
  - Delta + E484K
  - Delta RBD Abs depleted (x D614G PV)
  - D614G RBD Abs depleted (x D614G PV)
  - Delta RBD Abs depleted (x Delta PV)

# specify the "wildtype" virus for the purpose of this study
wildtype_virus: Delta

virus_subsets:
  mutneuts:
    - D614G
    - Delta
    - Delta + K417N
    - Delta + E484K
    - Delta RBD Abs depleted (x Delta PV)
  mutneuts_het:
    - D614G
    - Delta
    - Delta + K417N
    - Delta + E484K
    - Delta RBD Abs depleted (x D614G PV)
    - D614G RBD Abs depleted (x D614G PV)
    - Delta RBD Abs depleted (x Delta PV)
  # depletions:
  #   - D614G
  #   - Delta
  #   - Delta RBD Abs depleted (x D614G PV)
  #   - D614G RBD Abs depleted (x D614G PV)
  #   - Delta RBD Abs depleted (x Delta PV)
