# config for analysis
aggregate_fract_infect_csvs: results/neut_titers/fracinfect.csv

elisa_data_dir: data/rbd_depletion_elisas
elisa_data_files:
  - 08Oct21_ELISA.csv
  - 15Oct21_ELISA.csv
  - 06Dec21_ELISA.csv
  - 08Dec21_ELISA.csv
  - 08Dec21_D614G_ELISA.csv
  - 20Dec21_D614G_ELISA.csv

depletions:
  - mock depleted
  - 1x depleted
  - 2x depleted
  - 3x depleted
  - 4x depleted

previous_studies_rbd_depletions:
  infection: data/previous_studies_neuts/RBD_depletion_b1351_haarvi.csv
  moderna: data/previous_studies_neuts/RBD_depletion_moderna.csv

depletions_NT50_LOD:
  Delta breakthrough: 25
  primary Delta infection: 25
  2x BNT162b2: 25
  2x mRNA-1273: 25
  primary Beta infection: 25
  ancestral infection: 20

depletion_subsets:
  vax_vs_infection:
    2x BNT162b2 D614G spike: "2x\nBNT162b2\n(D614G spike)"
    2x mRNA-1273 D614G spike: "2x\nmRNA-1273\n(D614G spike)"
    ancestral infection D614G spike: "ancestral\ninfection\n(D614G spike)"
    primary Beta infection Beta spike: "primary\nBeta infection\n(Beta spike)"
    primary Delta infection Delta spike: "primary\nDelta infection\n(Delta spike)"
  breakthrough:
    Delta breakthrough D614G spike: "Delta\nbreakthrough\nafter 2x mRNA\n(D614G spike)"
    Delta breakthrough Delta spike: "Delta\nbreakthrough\nafter 2x mRNA\n(Delta spike)"
  mix_match:
    2x BNT162b2 Delta spike: "2x BNT162b2\n(Delta spike)"
    primary Delta infection D614G spike: "primary\nDelta infection\n(D614G spike)"
  heterologous:
    2x BNT162b2 Delta dep x D614G PV spike: "2x\nBNT162b2\nDelta RBD Abs dep\n(D614G PV)"
    Delta breakthrough Delta dep x D614G PV spike: "Delta breakthrough\nDelta RBD Abs dep\n(D614G PV)"
    primary Delta infection Delta dep x D614G PV spike: "primary\nDelta infection\nDelta RBD Abs dep\n(D614G PV)"


# enter all the samples and stuff to ignore here
neut_samples_ignore: False

# the neutralization limit of detection is equal to the starting dilution
NT50_LOD: 25

rbd_depletions_date:
  - 2021-11-12
  - 2021-11-25
  - 2021-12-12
  - 2021-12-22
  - 2022-01-06

heterologous_depletions_dates:
  - 2021-11-25
  - 2022-01-06

sample_key_file: data/sample_key.csv

sample_type_order:
  - 2x BNT162b2
  - Delta breakthrough
  - primary Delta infection

virus_key_mutneuts: # how to rename viruses for analyzing mutneuts
  RBD antibodies depleted (D614G spike): D614G RBD Abs depleted (x D614G PV)
  mock depletion (D614G spike): D614G
  RBD antibodies depleted (Delta spike): Delta RBD Abs depleted (x Delta PV)
  mock depletion (Delta spike): Delta
  Delta RBD antibodies depleted x D614G spike PV: Delta RBD Abs depleted (x D614G PV)
  Delta_E484K: Delta + E484K
  Delta_K417N: Delta + K417N
  Delta: Delta

virus_order:
  - D614G
  - Delta
  - Delta + K417N
  - Delta + E484K
  - Delta RBD Abs depleted (x D614G PV)
  - D614G RBD Abs depleted (x D614G PV)
  - Delta RBD Abs depleted (x Delta PV)

# specify the "wildtype" virus for the purpose of this study
wildtype_virus: Delta

virus_subsets:
  mutneuts:
    - D614G
    - Delta
    - Delta + K417N
    - Delta + E484K
    - Delta RBD Abs depleted (x Delta PV)
  mutneuts_het:
    - D614G
    - Delta
    - Delta + K417N
    - Delta + E484K
    - Delta RBD Abs depleted (x D614G PV)
    - D614G RBD Abs depleted (x D614G PV)
    - Delta RBD Abs depleted (x Delta PV)

previous_studies_mutneuts:
  infection: data/previous_studies_neuts/mutneuts_beta_paper.csv
  moderna: data/previous_studies_neuts/mutneuts_moderna_paper.csv

combined_plot:
  - D614G
  - Delta
  - Delta + K417N
  - Delta + E484K
  - Delta RBD Abs depleted (x Delta PV)
  - D614G + K417N
  - D614G + E484K
  - D614G RBD Abs depleted (x D614G PV)

combined_plot_group_order:
  - 2x BNT162b2
  - Delta breakthrough
  - primary Delta infection
  - 2x mRNA-1273 (day 100-150)
  - ancestral infection (day 30-60)
  - ancestral infection (day 100-150)

combined_plot_background_order:
  - Delta background
  - D614G background
